### ISSUE TITLE
testing against sass 3.3 & sass 3.4

### ISSUE THREAD

**Issue by bolandrm** [sass/sassc-ruby#10]
do we want to set up tests against both sass 3.3 and 3.4?

**Comment by edward** [comment]
Ah, because of the new dependency on the Sass gem?

I think testing against 3.4 is probably sufficient for now, especially if we want to focus on getting the project to a 1.0, “all the options/features you expect work”.

**Comment by edward** [comment]
(Also, this is me inserting my foot into my mouth after I went to see that we’re already beyond 1.0 in semver on this project…)

**Comment by bolandrm** [comment]
i like to go to 1.0 sooner rather than later, especially since i'm already using this in production.  the api is unlikely to dramatically change

**Comment by edward** [comment]
Sorry – words are hard sometimes – I meant that if we’re going to spend time working on this thing, I think we should spend it on making sassc-ruby more feature-complete/parity than on supporting consumer apps that require Sass 3.3
