### ISSUE TITLE
Update ffi dependency

### ISSUE THREAD

**Issue by morgoth** [sass/sassc-ruby#100]
`ffi` gem released version 1.10.
Can the sassc gem dependency be relaxed to include this release? https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1100--2019-01-06

**Comment by aried3r** [comment]
There's also already a (closed) PR for this! #99.

**Comment by bolandrm** [comment]
completed  https://github.com/sass/sassc-ruby/pull/102

**Comment by ut** [comment]
IMO the dependency has not been relaxed enough, PR #102 contains

`spec.add_dependency "ffi", "~> 1.9"`

but current FFI version is 1.10 

(FFI 1.10 is required by to others gems (like rb-inotify) which breaks my bundle install)

**Comment by aried3r** [comment]
@ut, `~> 1.9` will also match `1.10`. Indeed it's the same as `['>= 1.9', '< 2.0']` if I'm not mistaken. The only thing missing is a release with this change.

**Comment by bolandrm** [comment]
2.0.1, which includes this change, was released this morning

**Comment by aried3r** [comment]
Oh, I didn't check for updates today so far, good to know. Thanks for the release!

**Comment by ut** [comment]
Thanks @aried3r for the info, thanks @bolandrm for the release!
