### ISSUE TITLE
sassc-ruby can't be used with older Ruby, such as from older Linux distros' package repositories

### ISSUE THREAD

**Issue by DeeDeeG** [sass/sassc-ruby#106]
Hi,

I'm reporting this issue on behalf of some `bootstrap-sass` users, which is a gem that depends on `sassc-ruby`. (See this issue here: https://github.com/twbs/bootstrap-sass/issues/1182)

These users have trouble installing sassc-ruby due to its dependency on at least Ruby 2.3.3.

---

In general, some users currently depend on Ruby from distro package repositories. This is especially true of automatically managed environments, like Ansible configs, Docker images, Vagrant boxes etc. These users may be stuck on an older operating system version for one reason or another.

[Debian before stretch](https://packages.debian.org/search?keywords=ruby&searchon=names&exact=1&suite=all&section=all) and [Ubuntu before Bionic](https://packages.ubuntu.com/search?keywords=ruby&searchon=names&exact=1&suite=all&section=all), for instance, have Ruby older than 2.3.3 in their repositories. [CentOS 7](http://mirror.centos.org/centos/7/os/x86_64/Packages/) also has an older ruby version in its repos. Specifically, these are the versions available last I checked:

- Ubuntu Trusty: [1.9.3](https://packages.ubuntu.com/trusty/ruby)
- CentOS 7: [2.0.0](http://mirror.centos.org/centos/7/os/x86_64/Packages/ruby-2.0.0.648-33.el7_4.x86_64.rpm)
- Debian Jessie: [2.1.5](https://packages.debian.org/jessie/ruby)
- Ubuntu Xenial: [2.3.1](https://packages.ubuntu.com/xenial/ruby)

So with the latest Ruby from the distribution's package repos, these users can't install SassC-ruby.

---

For these users, perhaps this gem can be tested with older Ruby, and the [gemspec](https://github.com/sass/sassc-ruby/blob/250bdc4a35eb0d30a410e4e509e24617fee4d7ef/sassc.gemspec#L22) file can be updated to allow older Ruby, such as can be found in the distributions'  package repos?

**Comment by DeeDeeG** [comment]
Hi again folks, here's an update:

I tried running Travis CI on every minor release of Ruby back to 1.9.x. The result was that the Travis CI build failed for 1.9.3, but succeeded for 2.0.0, 2.1.9, 2.2.10, as well as the usual 2.3.7+.

Here's a link to my Travis CI results: https://travis-ci.com/DeeDeeG/sassc-ruby/builds/100168686

_(Tests are based on this branch: https://github.com/DeeDeeG/sassc-ruby/tree/Ruby-2.0.0 ([@19f07df](https://github.com/DeeDeeG/sassc-ruby/commit/19f07dfc2790173f8a73fe0bfa1310fcdbbd63ce)))_

---

If you'd be okay with this as a pull request, let me know. I didn't want to blast your CI with a queue of 6 builds at once though, so I'm probably not going to submit it as a PR unless I hear back from someone here.

Thanks! Sincerely,

\- DeeDeeG

**Comment by dracmaAgil** [comment]
Hi, I have the same issue, I'm using linux mint and ruby 2.3.1 and there is  no a ruby 2.3.3 version listed, the latest stable version is 2.3.1, 2.4.0 is not stable yet, what can I do to avoid this problem?

**Comment by dracmaAgil** [comment]
> Hi, I have the same issue, I'm using linux mint and ruby 2.3.1 and there is no a ruby 2.3.3 version listed, the latest stable version is 2.3.1, 2.4.0 is not stable yet, what can I do to avoid this problem?

Hi again, I solve this updating ruby-build (I'm usign rbenv) with this command "cd /home/dracma/.rbenv/plugins/ruby-build && git pull && cd -", after uodate, I list ruby vrsion ad there are from 2.3.2 to 2.3.8. I hoe this could help you guys!
