### ISSUE TITLE
Upgrade libsass to 3.5.5

### ISSUE THREAD

**Issue by DWSR** [sass/sassc-ruby#111]
We are unable to upgrade this gem because libsass 3.5.2 has a [regression regarding custom property values](https://github.com/sass/libsass/pull/2610) that was fixed in 3.5.5. Is there any way to get a minor rev published that includes a libsass version with the fix?

**Comment by DWSR** [comment]
I saw that https://github.com/sass/sassc-ruby/pull/94 was proposed which will close this issue. Any chance this will be merged soon?

**Comment by bolandrm** [comment]
Upgraded to libsass 3.6.0.   Please try using sassc-ruby `2.1.0.pre1` and let me know how it goes.
