### ISSUE TITLE
Precompiled binaries for windows

### ISSUE THREAD

**Issue by CAMOBAP795** [sass/sassc-ruby#126]
Is there any plans to 'embed' precompiled `libsass` library into the gem, to make installation on windows more user-friendly

Thanks

**Comment by glebm** [comment]
Yes, this will be in the next release (for mingw only, not mswin).

**Comment by bolandrm** [comment]
Version `2.1.0.pre2` released.  Please give it a test!

**Comment by CAMOBAP795** [comment]
Works for me, thanks
