### ISSUE TITLE
No command-line tool?

### ISSUE THREAD

**Issue by henrik** [sass/sassc-ruby#134]
Hi,

Did I just miss it, or does `sassc-ruby` not come with a command-line tool, like I believe the Ruby version did?

I assume the idea is that one can install https://github.com/sass/sassc to get a command-line tool?

If anyone else finds their way here, I did this in one project to avoid installing the command-line tool:

``` ruby bin/scss_to_css.rb
#!/usr/bin/env ruby

require "sassc"
	
input_file = ARGV[0]
output_file = ARGV[1]
	
scss = File.read(input_file)
css = SassC::Engine.new(scss).render
	
File.write(output_file, css)
```

Used like: `bundle exec bin/scss_to_css.rb input.scss output.css`

**Comment by DeeDeeG** [comment]
HI, I don't work on/maintain this project, but I do use the gem for a project. FWIW, there is this message upon installing the old ruby sass gem:

```
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new

  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the

  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:

  https://sass-lang.com/blog/posts/7828841
```

It recommends using Dart Sass. Not sure if that suits your project's needs.
