### ISSUE TITLE
Support 4 and 8 Digit Hex Codes

### ISSUE THREAD

**Issue by dlinch** [sass/sassc-ruby#135]
Hello,

Our project does some color math for theming for our customers, and we build a programmatic hex code with 8 digits, which is a valid CSS spec with wide [adoption](https://caniuse.com/#search=hex). However, the sassc library does not parse 4 and 8 digit hex codes at the moment.

We were doing some css parsing through Haml and Tilt, but ultimately they delegate to the sassc library, and as referenced from the issue I originally opened on Tilt, (https://github.com/rtomayko/tilt/issues/337) sassc says it will eventually parse 4 and 8 digit hex codes. This issue is a formal request for that functionality.

**Comment by bolandrm** [comment]
This issue is likely best raised in the main libsass repo, this library is just a wrapper around that.
