### ISSUE TITLE
Bundling Error

### ISSUE THREAD

**Issue by lostmahbles** [sass/sassc-ruby#140]
When trying to bundle from latest:
```
  gem "sassc", github: 'sass/sassc-ruby', ref: '84e63a89718a03ba3c5abeb8eb07f4a95a59a7ff'
```

Getting the following when bundling:
```
/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
```
which then hangs.

This appears to be a result of merging #138.

**Comment by bolandrm** [comment]
temporary issue or something?

**Comment by ahorek** [comment]
The code doesn't run when bundling. Could you try previous commit?

**Comment by lostmahbles** [comment]
I tried 4 different refs and it happened on all of them. I think it must've been a local configuration issue. When I blew away the local clone of the gem and reinstalled it worked fine.
