### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by someone29926** [sass/sassc-ruby#18]
Coincidentally the gem seems to install just fine however when I actually try to use it as a drop-in replacement for sass-rails I get the following upon trying to start a Rails server:

Uncaught exception: Could not open library 'C:/tools/ruby21/lib/ruby/gems/2.1.0/gems/sassc-1.6.0/ext/libsass/lib/libsass.so': The specified module could not be found.

Thoughts?

**Comment by bolandrm** [comment]
I have not done any development on Windows.

I believe in order to support Windows, we'd need to swap the occurrences of `.so` with `.dll` if the user is on a windows platform.

**Comment by huangyq23** [comment]
Do we have any plan of switching to a `rake-compiler` solution so that we can have pre-compiled gem for different platforms?

**Comment by johnnyshields** [comment]
:+1: for rake-compiler. It should not be too difficult to setup.

**Comment by Coridyn** [comment]
Just encountered the same error on Windows.

I fixed the problem by [editing the Makefile](https://github.com/sass/libsass/blob/master/Makefile#L69) and forcing libgcc to be statically linked.

Change all of these variables to 1:
```
    STATIC_ALL       ?= 1
    STATIC_LIBGCC    ?= 1
    STATIC_LIBSTDCPP ?= 1
```

Once that's sorted out Windows can load the `.so` file fine - no need to swap to loading the `.dll`.

I found the answer in this old [ruby-ffi post](http://ffi.github.io/ruby-ffi-archive/messages/20110430-Re_%5Bruby-ffi%5D%20need%20help%20loading%20a%20library-805.html) - statically linking the dependency sorts it out.

**Comment by johnnyshields** [comment]
@Coridyn it looks like this is already being done on Windows, see this line:

```
# enable mandatory flag
ifeq (MinGW,$(UNAME))
```

**Comment by Coridyn** [comment]
In that case it looks like the UNAME check needs to be swapped so MinGW takes precedence over Windows:

```
ifneq (,$(findstring /cygdrive/,$(PATH)))
	UNAME := Cygwin
else
	ifneq (,$(findstring WINDOWS,$(PATH)))
		UNAME := Windows
	else
		ifneq (,$(findstring mingw32,$(MAKE)))
			UNAME := MinGW
		else
			ifneq (,$(findstring MINGW32,$(shell uname -s)))
				UNAME = MinGW
			else
				UNAME := $(shell uname -s)
			endif
		endif
	endif
endif
```

On my machine UNAME ends up with the value `Windows` so it tries to build a dynamic instead of a static library.

**Comment by johnnyshields** [comment]
Should raise this on Libsass library

**Comment by schneems** [comment]
Wanted to chime in here, the Sprockets sassc integration is failing on Windows: https://github.com/rails/sprockets/pull/349

I dug in and found one obvious place that needs to be fixed. The path separators is different in different operating systems https://github.com/schneems/sassc-ruby/pull/1 I believe there need to be changes made to the C code but i'm not as familiar there, maybe if someone can point out where we're splitting out the path again that would be great.

I'm working on a windows VM right now, ideally once we get windows working it would be great to get Appveyor set up to run tests and let us know about any failures.
