### ISSUE TITLE
update embedded version of libsass to 3.6.3

### ISSUE THREAD

**Issue by pravi** [sass/sassc-ruby#190]
3.6.3 fixes some security issues in libsass

**Comment by swistaczek** [comment]
👍 +1

**Comment by pravi** [comment]
It is merged in master https://github.com/sass/sassc-ruby/commit/dc0e2518b081c42b4e458c3e7fdf2635c24f5323 it'd be nice if there is a new release.

**Comment by bolandrm** [comment]
Released 2.3.0
