### ISSUE TITLE
New release including d49229898c5c4e8a142129bdb5043bb01a479812

### ISSUE THREAD

**Issue by rafaelfranca** [sass/sassc-ruby#195]
#146 is still open and we have a fix, or an automatic workaround for it, for more than 6 months sitting on master.

Can we please do a new release including that commit?

**Comment by bolandrm** [comment]
I attempted to do a release a couple weeks ago and the build process is failing.  I don't have the time to do much other than occasionally review and merge PRs and do releases.   cc @glebm

**Comment by casperisfine** [comment]
> the build process is failing

You mean CI? Or the process to release the gem?

If we can help let us know.

**Comment by bolandrm** [comment]
@casperisfine There's an issue running `bundle exec rake gem:native`.  I can't remember the exact error, but it was related to `rake-compiler-dock`.

**Comment by casperisfine** [comment]
I see. Yeah rake-compiler-docker was only recently fixed, and AFAIK it's still quite wonky.

However it was my understanding that sass-c was no longer precompiling the gem, so this step can probably be skipped.

**Comment by casperisfine** [comment]
Scratch that, seem like the 2.1.x releases are precompiled, `2.0.x` aren't.

**Comment by casperisfine** [comment]
```
Package g++-multilib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'g++-multilib' has no installation candidate
rake aborted!
```

**Comment by bolandrm** [comment]
2.3.0 released.
