### ISSUE TITLE
Invalid CSS generated with 2.3.0 (Nesting + child combinator + selector lists + interpolation)

### ISSUE THREAD

**Issue by abrom** [sass/sassc-ruby#198]
I noticed some invalid CSS being generated after updating from 2.2.1 to 2.3.0. I suspect this is more likely an upstream `libsass` issue but thought it best to raise here first.

Given the following scss:
```
$abc: 'qux';

.foo {
  > .bar.#{$abc},
  & > .baz {
    color: blue;
  }
}
```

With 2.2.1 you get the expected (valid) output:
```
.foo > .bar.qux,
.foo > .baz {
  color: blue;
}
```

With 2.3.0 however you get the following invalid CSS (missing `.foo` at the start of the first selector):
```
> .bar.qux, .foo > .baz {
  color: blue;
}
```

The issue only shows itself when you have the combination of:
* Nesting
* Child combinator (without leading parent selector)
* Multiple nested styles in a selector list
* Some sort of interpolation -

_N.B. i've found the output is broken if there is interpolation anywhere in the nested list of selectors_

If any one of these rules is removed the output is as expected

If a parent selector is added before the child combinator ie `& > .bar.#{$abc},` it also outputs as expected.

I only noticed this because after updating the `sassc` gem a number of `bootstrap-sass` (v3) styles were broken

Thoughts?

**Comment by fernandoluizao** [comment]
I notice that too. Also using bootstrap-sass v3.

**Comment by toncid** [comment]
Any chances of fast tracking this fix?
