### ISSUE TITLE
Fails to install on JRuby + Windows

### ISSUE THREAD

**Issue by slonopotamus** [sass/sassc-ruby#214]
See [test project](https://github.com/slonopotamus/sassc-jruby-test/blob/master/Gemfile) and [build log](https://github.com/slonopotamus/sassc-jruby-test/runs/1026295911?check_suite_focus=true#step:4:17).

I've also reported this bug as ruby/setup-ruby#81 because I'm not sure what party is to blame here.

**Comment by eregon** [comment]
This sounds like an issue of JRuby to me:
```
Installing sassc 2.4.0 with native extensions
C:/Users/runneradmin/.rubies/jruby-9.2.13.0/lib/ruby/stdlib/rubygems/ext/builder.rb:76: warning: unsupported popen option: err
C:/Users/runneradmin/.rubies/jruby-9.2.13.0/lib/ruby/stdlib/rubygems/ext/builder.rb:76: warning: unsupported popen option: err
C:/Users/runneradmin/.rubies/jruby-9.2.13.0/lib/ruby/stdlib/rubygems/ext/builder.rb:76: warning: unsupported popen option: err
process_begin: CreateProcess(NULL, cc -I. -I/include/java -IC:/Users/runneradmin/.rubies/jruby-9.2.13.0/lib/ruby/include/ruby/backward -IC:/Users/runneradmin/.rubies/jruby-9.2.13.0/lib/ruby/include -I. -I./libsass/include -fPIC -fno-omit-frame-pointer -fno-strict-aliasing -fexceptions -DLIBSASS_VERSION=\"3.6.4\" -m64 -march=native -mtune=native -o c99func.o -c ./libsass/src/c99func.c, ...) failed.
make (e=2): The system cannot find the file specified.

mingw32-make: *** [Makefile:204: c99func.o] Error 2
```
https://github.com/jruby/jruby/blob/2f0c49000a4479a259b3e54db9898accb749d44f/lib/ruby/stdlib/rubygems/ext/builder.rb#L75-L76

Could you report it there?

**Comment by slonopotamus** [comment]
Hmm... Google [says](https://stackoverflow.com/a/1240603) that `process_begin: CreateProcess(...) failed` message comes from `mingw32-make` and means that `cc` was not found on PATH. Why you think it is JRuby fault?

**Comment by slonopotamus** [comment]
Though I'm not sure why it searches for `cc` instead of something like `mingw-w32-gcc`.

**Comment by slonopotamus** [comment]
What puzzles me is that it does find `mingw32-make` (which is too a part of mingw/MSYS2, AFAIK), but doesn't find compiler. Possibly `cc` executable name is actually wrong.

Dunno, will try to reproduce this locally.

**Comment by slonopotamus** [comment]
Closing, everyone agreed that this needs to be fixed on `ruby/setup-ruby` side.
