### ISSUE TITLE
Pass absolute parent_path to Importer?

### ISSUE THREAD

**Issue by Coridyn** [sass/sassc-ruby#27]
I'm writing a custom importer for SassC and have run into an issue with globs and relative `parent_path` passed to importer.

__node-sass__ passes the absolute `parent_path` to its importers (https://github.com/sass/node-sass/commit/a474102df7cd072ae072ade19635b697346a9663) and it would make things easier if the two libraries called importers with the same parameters.

Could the importer be passed the absolute `parent_path` instead of relative?

## Example

Here's an example that shows the issue:

```scss
// main.css.scss
@import "user1/_all-vars";

body { 
    color: $color;
}
```

```scss
// user1/_all-vars.scss
@import "vars/*";
```

```scss
// user1/vars/_user-vars.scss
$color: blue;
```

```
// user2/vars/_user-vars.scss
$color: red;
```

When rendering `main.css.scss` the importer receives these parameters:

```bash
path: 'user1/_all-vars'
parent_path: '/root/main.css.scss'
# ✓ My importer resolves to -> /root/user1/_all-vars.scss


path: 'vars/*'
parent_path: '/user1/_all-vars'
# ✓ My importer returns a relative import statement -> @import "vars/_user-vars.scss";


path: 'vars/_user-vars.scss'
parent_path: '/vars/*'
# ✗ Ambiguous - resolve to which file?
#    /root/user1/vars/_user-vars.scss
#    /root/user2/vars/_user-vars.scss
```

**Comment by bolandrm** [comment]
This seems very reasonable - are you able to open a PR for this?  I can test it against sassc-rails.
