### ISSUE TITLE
Sassc cannot be bundled with --path argument

### ISSUE THREAD

**Issue by edwinvdgraaf** [sass/sassc-ruby#42]
Thanks for the amazing work, your project makes working with sass in a ruby environment very easy. 
​
Yesterday I got into an issue with `sassc` not being able to compile on our CI after updating our runner to ruby-2.3.0 when using the --path (ie. `bundle install --path .bundle/vendor`) argument with bundler so we can store the gems relative to our project (usefull for caching). 
​
Since then I did some troubleshooting with the following results:
​
- It happens both on our CI (docker) and locally Mac OSX when ruby-2.3.0 is used. With the following Gemfile:

```
source 'https://rubygems.org'
gem "sassc"
```
- In both situations I get the following error:

```
bundle install --path .bundle/vendor
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing ffi 1.9.10 with native extensions
Installing sass 3.4.22
Using bundler 1.11.2
Installing sassc 1.9.0 with native extensions
​
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
​
    current directory: /Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0/gems/sassc-1.9.0/ext
rake RUBYARCHDIR=/Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/sassc-1.9.0 RUBYLIBDIR=/Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/sassc-1.9.0
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'rake' (>= 0.a) among 7 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0', execute `gem env` for more information
  from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
  from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
  from /usr/local/var/rbenv/versions/2.3.0/bin/rake:22:in `<main>'
​
rake failed, exit code 1
​
Gem files will remain installed in /Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0/gems/sassc-1.9.0 for inspection.
Results logged to /Users/edwin/Projects/zandbak/ruby-sassc/.bundle/vendor/ruby/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/sassc-1.9.0/gem_make.out
An error occurred while installing sassc (1.9.0), and Bundler cannot continue.
Make sure that `gem install sassc -v '1.9.0'` succeeds before bundling.
```

​
- Manually `cd`'ing to the `.bundle/vendor/ruby/2.3.0/gems/sassc-1.9.0/ext` and calling `$ rake` works. 
  ​
- Gem installation with `gem install sassc -i .bundle/gem-sassc` works

​
I am a bit in the dark on how to proceed hence this issue report, hoping you may have some pointers.

**Comment by huwd** [comment]
I'm also having this problem - problem for me as I'm trying to deploy to GitLab pages to (enjoy LetsEncrypt https support), which seems to require you to have all gems bundled in vendor/

Anyone got any advice on how to get around this?

**Comment by edwinvdgraaf** [comment]
You can try to add `gem "rake"` to your `Gemfile`. That works for us.

**Comment by Magi-KS** [comment]
I got it to work after updating GCC packages

**Comment by ryanjwilke** [comment]
The `gem "rake"` thing worked for us too.

**Comment by bolandrm** [comment]
Closing this, should be resolved by #63

**Comment by grasshopper74** [comment]
I had the same problem and was solved by installing `g++`

**Comment by xiazhaoyang** [comment]
It's great, it works for me~~
