### ISSUE TITLE
!optional ignored when using variables with @extend

### ISSUE THREAD

**Issue by kagagnon** [sass/sassc-ruby#43]
I've got a bug in a Rails app using the gem `sassc-rails`. When using variable in `@extend` directive, I receive this error:

```
SassC::SyntaxError in Page#home

Error: "%default-grid" failed to @extend "%default-gutter".
       The selector "%default-gutter" was not found.
       Use "@extend %default-gutter !optional" if the extend should be able to fail.
        on line 303 of vendor/assets/bower_components/gridle/sass/gridle/_mixins.scss
>>             @extend %#{$_gridle_current_stateName}-#{$package} !optional;
   -------------------^
```

**This can be reproduced easily by doing:**

```
$test : 'name';

// Doesn't works
.class{
    @extend %#{$test} !optional;
}

// Works
.class{
    @extend %hello !optional;
}
```

---

I'm not sure where this problem is coming from, but the same code works with `sass-rail` (not `libSass`) and `node-sass` (`libSass`), so I d'ont think it is a `libSass` compiler error.

**Comment by bolandrm** [comment]
closing as stale issue, please let me know if it is still a problem.
