### ISSUE TITLE
Stop importing value types from Ruby Sass

### ISSUE THREAD

**Issue by nex3** [sass/sassc-ruby#71]
Once Dart Sass 1.0.0 releases, Ruby Sass will be deprecated. A year later, it will reach end-of-life and will no longer be maintained. To prepare for this, sassc-ruby should stop using value types from `Sass::Script` and should take ownership of them directly.

It would probably make sense to put the value types in a separate package from sassc-ruby, so that they can be shared with the planned gem that will embed Dart Sass (sass/dart-sass#249).

**Comment by bolandrm** [comment]
Closing this, since we have work in progress here:  https://github.com/sass/sassc-ruby/pull/85
