### ISSUE TITLE
Update libsass version

### ISSUE THREAD

**Issue by dennisvandehoef** [sass/sassc-ruby#73]
This gem uses: v3.4.3, the latest version is v3.5.2.

Since this gem is being proposed as an alternative to the now deprecated ruby-sass [here](http://sass.logdown.com/posts/7081811) an up-to-date version of libsass might be a cool idea.

**Comment by yjukaku** [comment]
I agree. This repo is over a year behind libsass, it seems.

This also would solve the issue I'm having in #77 , I believe.

**Comment by bolandrm** [comment]
Hey, released 1.12.0, please give it a try!
