### ISSUE TITLE
Ruby Sass End-of-Life: 26 March 2019

### ISSUE THREAD

**Issue by chriseppstein** [sass/sassc-ruby#75]
https://github.com/rails/rails/issues/32896
https://github.com/rails/sass-rails/issues/420

It sounds like rails intends to make this the canonical replacement for `sass-rails` and the `sass` ruby gem.

This gem depends on the deprecated sass gem for integration with Sass Value types and some utility code.

If you'd like to extract the shared code to a separate gem that can be used by both this library and ruby-sass and be made a maintainer for the shared library, please let me know and I can assist you with creating the repos and any permissions.

**Comment by nex3** [comment]
There are now only nine months remaining to migrate this package away from importing Ruby Sass. Is any work being done on that? @bolandrm

**Comment by bolandrm** [comment]
I'm more or less using webpack/webpacker for everything now, so I don't currently have any plans to take this on.  It shouldn't be too complicated though, so if someone from the community would like to open a PR i'll be sure to review and merge.

**Comment by bolandrm** [comment]
Closing this - work in progress here:  https://github.com/sass/sassc-ruby/pull/85
