### ISSUE TITLE
Question: SassC with Bundler

### ISSUE THREAD

**Issue by dannycolin** [sass/sassc-ruby#84]
I've create a rake task that call SassC::engine but I was wondering if it is (or will be) possible to use sassc directly as a commandline with Bundler like it's possible with sass. For example

`bundle exec sassc [options] [input] [output]`

**Comment by bolandrm** [comment]
Hello, we don't currently support this, and I don't have any plans to implement it at this point.  I would consider merging a PR that implements this functionality.
