### ISSUE TITLE
[SASSC 2.0] Sass::Script::String

### ISSUE THREAD

**Issue by ahorek** [sass/sassc-ruby#89]
Hi @csuhta 
I tested your PR https://github.com/sass/sassc-ruby/pull/85 and found out that you removed Sass::Script::String references in favor of Sass::Script::Value::String
https://github.com/sass/sassc-ruby/pull/85/files#diff-36146a65a77915929f0dd69a9bb0c214L42

but the change makes it incompatible with sprockets
https://github.com/rails/sprockets/blob/master/lib/sprockets/sass_processor.rb#L149

should we make the change in sprockets or sassc?

**Comment by bolandrm** [comment]
Hey @ahorek ,

There would have to be a change made to sprockets in order to support this.  In the mean time, I'm working on update SassC-Rails, which overrides Sprockets to support the new class names.

https://github.com/sass/sassc-rails/pull/109

**Comment by ahorek** [comment]
great, thanks!
