### ISSUE TITLE
libsass.so stays in ext/ - but should be in lib/

### ISSUE THREAD

**Issue by coolo** [sass/sassc-ruby#95]
I would have provided a PR if I knew rake a little better. But openSUSE packages gems so that ext/ is left as sources not for production.

Every other gem moves/copies libraries required to lib/, sassc sticks out there.

**Comment by anatol** [comment]
There is actually more information here.

Starting from a while ago rubygems installs dynamic libraries to `/usr/lib/ruby/gems/$VER/extensions/x86_64-linux/$VER/` as a primary destination. Installing `*.so` files to `lib` is done for [historical reason](https://github.com/rubygems/rubygems/commit/1c5f4b3fc038a5553523bfd93c98184f712abae2). Some distros such as Fedora and Arch Linux disabled installation to `lib` already and the `so` files available under `extensions` only.
