### ISSUE TITLE
use system libsass rather than compile each time new

### ISSUE THREAD

**Issue by ebgc** [sass/sassc-ruby#97]
hi

duplicate to 'Sassc Ruby should detect presence of existing libsass.so' (https://github.com/sass/sassc-ruby/issues/8) - i would like to see this re-opened !

tx

**Comment by bolandrm** [comment]
I have no plans to add this feature; a contributor will have to create a pull request.

**Comment by glebm** [comment]
By the way, the original motivation for #8 is that installing on CI is slow. This will be mitigated in the next version by the precompiled gems for Windows (mingw) and Linux.

**Comment by julian7** [comment]
@glebm the precompiled version doesn't work on alpine. Apparently, the linux package assumes you have libc too.
